version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: job-importer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: job_importer
    volumes:
      - mongodb_data:/data/db
    networks:
      - job-importer-network

  redis:
    image: redis:7-alpine
    container_name: job-importer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - job-importer-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: job-importer-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/job_importer?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/logs:/app/logs
    networks:
      - job-importer-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: job-importer-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - job-importer-network

volumes:
  mongodb_data:
  redis_data:

networks:
  job-importer-network:
    driver: bridge
